In [0]:
import torch

x = torch.tensor([[[1,2],[3,4]], [[1,5], [10, 11]]])
x[1][0][1] = 100
x


torch.Size([3, 5, 2])

In [0]:
x = torch.zeros([3, 5, 2])
x.shape

torch.Size([3, 5, 2])

In [0]:
x = torch.rand([2, 3, 10])
x

tensor([[[0.1417, 0.8528, 0.8601, 0.2832, 0.2017, 0.8399, 0.6148, 0.8488,
          0.2489, 0.0107],
         [0.6277, 0.1248, 0.4174, 0.8193, 0.0121, 0.3492, 0.7941, 0.7136,
          0.9536, 0.3662],
         [0.7989, 0.4160, 0.2307, 0.0746, 0.3366, 0.0885, 0.2535, 0.0580,
          0.6413, 0.0033]],

        [[0.8751, 0.6099, 0.5603, 0.9533, 0.1436, 0.1307, 0.1409, 0.7332,
          0.5394, 0.1978],
         [0.1570, 0.1513, 0.8625, 0.7448, 0.6767, 0.6555, 0.4504, 0.1921,
          0.8618, 0.5491],
         [0.8714, 0.5159, 0.7835, 0.5830, 0.6879, 0.3757, 0.2801, 0.9098,
          0.9711, 0.8099]]])

In [18]:
x=torch.rand([2, 2, 3])
x

tensor([[[0.1994, 0.4321, 0.2360],
         [0.2563, 0.1969, 0.0685]],

        [[0.8199, 0.2968, 0.0059],
         [0.6473, 0.7264, 0.2166]]])

In [19]:
x = x.view([1, 12])
x

tensor([[0.1994, 0.4321, 0.2360, 0.2563, 0.1969, 0.0685, 0.8199, 0.2968, 0.0059,
         0.6473, 0.7264, 0.2166]])